apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}-runtime
  namespace: {{ .Values.Namespace }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  runtime.yaml: |
    {{ tpl (toYaml .Values.runtimeConfig) . | nindent 4 }}
