cilium:
  enabled: false
  Namespace: kube-system
  aksbyocni:
    enabled: true
  nodeinit:
    enabled: true

ingress-azure:
  enabled: true
  Namespace: kube-system
  appgw:
    environment: AZUREPUBLICCLOUD
    subscriptionId: 15e39dd4-0677-4bcd-bb45-d2deb5edda40
    resourceGroup: dev-akspoc-rapyder
    name: dev-akspoc-rapyder
  armAuth:
    type: workloadIdentity
    identityClientID: "3dfe02ad-9e42-48f3-96b5-03c5b601da67"
  rbac:
    enabled: true

karpenter:
  enabled: false
  Namespace: kube-system
  settings:
    azure:
      clusterName: ""
      clusterEndpoint: ""
  serviceAccount:
    name: karpenter-sa
    annotations:
      azure.workload.identity/client-id: 9c1f9087-a756-4806-8e11-54e4203564d9
  controller:
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi

keda:
  enabled: false
  Namespace: keda

minio-operator:
  enabled: false
  Namespace: minio-operator
