blob-csi-driver:
  enabled: false
  Namespace: kube-system
  workloadIdentity:
    clientID: "45e1167a-6924-4a16-9c2d-cfc6f41ad882"

ingress-azure:
  enabled: false
  Namespace: kube-system
  appgw:
    environment: AZUREPUBLICCLOUD
    subscriptionId: ""
    resourceGroup: "dev-akspoc-rapyder"
    name: "dev-akspoc-rapyder"
  armAuth:
    type: workloadIdentity
    identityClientID: ""
  rbac:
    enabled: true

promtail:
  enabled: true
  Namespace: default
#  config:
#    extraScrapeConfigs: []
      

cilium:
  enabled: false
  Namespace: kube-system
  aksbyocni:
    enabled: true
  nodeinit:
    enabled: true

karpenter:
  enabled: false
  Namespace: kube-system
  settings:
    azure:
      clusterName: ""
      clusterEndpoint: ""
  serviceAccount:
    name: karpenter-sa
    annotations:
      azure.workload.identity/client-id: 9c1f9087-a756-4806-8e11-54e4203564d9
  controller:
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi

keda:
  enabled: false
  Namespace: keda

minio-operator:
  enabled: false
  Namespace: minio-operator
